### ISSUE TITLE
Download issue resolved!

### ISSUE THREAD

**Issue by Catana791** [Catana791/Fading-Revelations#1]

**Comment by A-Vladimir** [comment]
But why did you need to clear everything, even the favorites?

**Comment by Catana791** [comment]
It was a corrupted directory. Don't ask me how or why

**Comment by Catana791** [comment]
The problem is just that the mod browser ingame can somehow now not find the mod anymore

**Comment by A-Vladimir** [comment]
btw is the shotgun turret supposed to hava a base or just the turret top?

**Comment by Catana791** [comment]
It normally has a base. Why?

**Comment by Catana791** [comment]
Oh wait I think in the code it still says BrustTurret and that type was removed in the v6 update let me check really quick

**Comment by Catana791** [comment]
Yes it still said BurstTurret. Fixed!

**Comment by Catana791** [comment]
One question: Can you still use the mod? When I try to install it using the Mod Browser or the Import mod from github it says can't find.

**Comment by A-Vladimir** [comment]
you are right it's no longer in the mod browser, it was there a short while ago after your reupload
