### ISSUE TITLE
Texture Bug

### ISSUE THREAD

**Issue by A-Vladimir** [Catana791/Fading-Revelations#15]
The Turret part of the Liquid Minigun is kinda on the side rather than in the middle.  
![Screenshot_20210316-093057_Mindustry](https://user-images.githubusercontent.com/18213814/111279212-c0743b00-863a-11eb-838b-a9cba1d69c6f.png)

**Comment by Catana791** [comment]
I will look into it.

**Comment by Catana791** [comment]
Well it seems like it is just a texture glitch on the icon because it works fine when placed down. I will see if I can use a trick to try and fix it but it will probably not work.

**Comment by Catana791** [comment]
Well it seems like it is just a texture glitch on the icon because it works fine when placed down. I will see if I can use a trick to try and fix it but it will probably not work.

**Comment by Catana791** [comment]
Well @A-Vladimir, I've been trying to get the sprite to not show like that but after 2 hours, I was still unable to do so. It does show normally when you place it but the icon is just weird. I will try to look into it again but for now, it has to stay like that, I am afraid. I am going to close this issue now. Thank you for reporting it!
