### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Arthur-The-Ok** [Catana791/Fading-Revelations#18]
![Captura de tela 2021-07-18 192645](https://user-images.githubusercontent.com/81048660/126083973-6c1f4ea9-3197-4e55-a232-50c6aabf28f4.jpg)
![Captura de tela 2021-07-18 193226](https://user-images.githubusercontent.com/81048660/126083978-274e470e-65f4-4710-b39a-9750da356472.jpg)
![Captura de tela 2021-07-18 193243](https://user-images.githubusercontent.com/81048660/126083982-d06954d3-6e75-42d1-b9da-b1ef5ed06d84.jpg)

**Comment by ThePythonGuy3** [comment]
Same thing happened to me, the mod is broken in v7

**Comment by ThePythonGuy3** [comment]
Go back to v6, and if you are in v6, well then idk

**Comment by Arthur-The-Ok** [comment]
Do you plan on moving the mod to V7? If no, it's ok

**Comment by ThePythonGuy3** [comment]
Ask the creator, not me

**Comment by Catana791** [comment]
It seems as though that would be an easy fix. I will leave the issue open until I fix it. Shouldn't take too long. And yes, this mod will be v7 compatible.

**Comment by Gugui322** [comment]
> It seems as though that would be an easy fix. I will leave the issue open until I fix it. Shouldn't take too long. And yes, this mod will be v7 compatible.

Do you know how to fix?

**Comment by Catana791** [comment]
I think so, yes.

**Comment by Catana791** [comment]
This has been resolved. As the mass driver made issues in the current version, too, it has been deleted. easy fix I guess :shrug:
