### ISSUE TITLE
heresy sprites

### ISSUE THREAD

**Issue by NewestGitHubber** [Catana791/Fading-Revelations#19]
i saw the drill and laser screenshot and i see heresy spriting, please fix
![image](https://user-images.githubusercontent.com/86703851/126338252-c660bd98-3422-4610-9a29-489feb6e4e8d.png)

**Comment by Catana791** [comment]
What in your eyes makes it heresy?

**Comment by ThePythonGuy3** [comment]
The corners, don't use angles that aren't 0, 45, 90, 135...

**Comment by Catana791** [comment]
This was fixed by now. No more heresy in this sprite.
