### ISSUE TITLE
Mod not showing up in Mod Browser or "Import mod from GitHub"

### ISSUE THREAD

**Issue by Catana791** [Catana791/Fading-Revelations#2]
Does anyone else have this issue? I can't install the mod.

**Comment by A-Vladimir** [comment]
yep, + the already installed version shows this after I used the reinstall button

**Comment by Catana791** [comment]
I can't see the screenshot.

**Comment by A-Vladimir** [comment]
![Screenshot_20210208-125300_Mindustry](https://user-images.githubusercontent.com/18213814/107216390-fd7e5980-6a0c-11eb-96bb-9dcb6baad838.png)

**Comment by A-Vladimir** [comment]
sry, on mobile over here

**Comment by Catana791** [comment]
Okay I fixed that

**Comment by Catana791** [comment]
Let me see

**Comment by Catana791** [comment]
No problem ;)

**Comment by Catana791** [comment]
Okay so now it works when you download the master zip file but it still does not show up in the mod browser.

**Comment by A-Vladimir** [comment]
Good thing I already have it installed, did the reinstall button again and it works without error.

**Comment by Catana791** [comment]
Okay fixes all the issues. The browser had trouble because it was looking for mindustry-extended wich I deleted so now that it is renamed, the "Import mod from GitHub" works again

**Comment by Catana791** [comment]
I will try to get it working with the mod browser again but at least it is now easily installable again.

**Comment by Catana791** [comment]
Have fun with the mod, @A-Vladimir
