### ISSUE TITLE
the tech tree for the mod does not load

### ISSUE THREAD

**Issue by littlekatter330** [Catana791/Fading-Revelations#34]
this is a unplayable bug

**Comment by Catana791** [comment]
Are you reffering to the large one for Serpulo that is separated?

**Comment by Catana791** [comment]
Because it loads just fine for me

**Comment by Catana791** [comment]
Also what is your game version?

**Comment by littlekatter330** [comment]
140.3

**Comment by littlekatter330** [comment]
found it

**Comment by Catana791** [comment]
So the issue os resolved now?
