### ISSUE TITLE
Bug/Issue

### ISSUE THREAD

**Issue by Dshadeslayer** [Catana791/Fading-Revelations#35]
**Describe the bug**
I am unable to see the item-trade terminals in the research tree. I do have a good few mods, so I am worried that it could possibly be conflicting with something. What it is conflicting with I am unsure, and I wish to not lose my campaign saves to test this, if possible.
**To Reproduce**
I go to the research tree, with a mod that allows me to see all items in the tree, and the item trade terminals are missing.
**Expected behavior**

**Screenshots**
https://i.imgur.com/hI8E5Cf.png
https://i.imgur.com/6UBJQJZ.png
These are just two screenshots of my tech tree- I'm very unsure if they even show up?
**Desktop (please complete the following information):**
Version: Latest as of 11/18/2022

**Additional context**

**Comment by Catana791** [comment]
I have separated the Fading Revelations Serpulo research tree from the Serpulo one. To find it, click on the button at the top of the screen and select Fading Revelations.
