### ISSUE TITLE
remove unused/deprecated classes when

### ISSUE THREAD

**Issue by yesC48** [Catana791/Fading-Revelations#39]
**What block/unit/etc is the balance issue about?.**
Mountains worth of unused/deprecated classes. They might heavily impact mod-to-mod compatibility or crashing probability.

**Is the block/unit/etc too strong/too weak?**
These unused/deprecated classes are so many I can't see how much RAM Mindustry allows itself to use.

**By how much should it be fixed?**
1. Download NewConsole mod by Mnemotechnician. (makes this easier.)
2. Check the console interface within said mod.
3. Slowly fix/replace the said classes.

**Comment by Catana791** [comment]
There have never been issues with this before but I was planning to clean up the console errors anyway so consider this as "in progress".

**Comment by yesC48** [comment]
noted

**Comment by Catana791** [comment]
@yesC48 this is done. All of the errors have been fixed. (There is one "error" left but that one has to stay because removing it would change the behaviour of that unit for some reason...)

**Comment by yesC48** [comment]
you should try to rewrite the said unit from scratch, can you?

**Comment by Catana791** [comment]
Nevermind my first statement. I was thinking that the range variable on the unit's weapon was making it behave the way I want it to when it was actually aimDst so, in short, I can fix that last "error" making Fading Revelations uses of deprecated classes a.s 0.

**Comment by Catana791** [comment]
Done
