### ISSUE TITLE
Balance Playtesters

### ISSUE THREAD

**Issue by Catana791** [Catana791/Fading-Revelations#4]
Hello. Anyone reading this, would you be interested in testing the mod and seeing if something is too strong/weak? If so, DM me "I am interested in balance playtesting." (Catana#8735) and we will see. Thank you in advance!

**Comment by Rem-Armiger** [comment]
What mod are you talking about? If so what is it? Sure side be intrested Sent from my Galaxy
-------- Original message --------From: Fresh791 <notifications@github.com> Date: 2/11/21  6:36 PM  (GMT+08:00) To: Fresh791/mindustry-extended <mindustry-extended@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Fresh791/mindustry-extended] Balance Playtesters (#4) 
Hello. Anyone reading this, would you be interested in testing the mod and seeing if something is too strong/weak? If so, DM me "I am interested in balance playtesting." @catana#8735 and we will see. Thank you in advance!

**Comment by Catana791** [comment]
I am talking about this mod right here. mindustry-extended. I would need help figuring out wether or not the turrets, units, etc. are too strong, too weak or perfectly balanced. If you are interested, DM me Catana#8735 on Discord.

**Comment by Rem-Armiger** [comment]
Oh that mod where I had installed yesterday, well umm uhSent from my Galaxy
-------- Original message --------From: Fresh791 <notifications@github.com> Date: 2/11/21  7:10 PM  (GMT+08:00) To: Fresh791/mindustry-extended <mindustry-extended@noreply.github.com> Cc: Rem-Armiger <remarmiger12@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [Fresh791/mindustry-extended] Balance Playtesters (#4) 
I am talking about this mod right here. mindustry-extended. I would need help figuring out wether or not the turrets, units, etc. are too strong, too weak or perfectly balanced. If you are interested, DM me Catana#8735 on Discord.

**Comment by Rem-Armiger** [comment]
I am very sorry if I have not responded over on discord I had just deleted yesterday and deleted my account, It will take sometime for me to respond as I said earlier I'm very sorry.Sent from my Galaxy
-------- Original message --------From: Fresh791 <notifications@github.com> Date: 2/11/21  7:10 PM  (GMT+08:00) To: Fresh791/mindustry-extended <mindustry-extended@noreply.github.com> Cc: Rem-Armiger <remarmiger12@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [Fresh791/mindustry-extended] Balance Playtesters (#4) 
I am talking about this mod right here. mindustry-extended. I would need help figuring out wether or not the turrets, units, etc. are too strong, too weak or perfectly balanced. If you are interested, DM me Catana#8735 on Discord.

**Comment by Catana791** [comment]
Don't be sorry. If you wanna help just DM me when you have your account back. No need to be sorry.

**Comment by Rem-Armiger** [comment]
Apparently I can't DM you if I'm not in a server you are in.

**Comment by Catana791** [comment]
As noone else commented I will now close the search for balance playtesters for now. Thank you!
