### ISSUE TITLE
Bug/Issue

### ISSUE THREAD

**Issue by Quolt** [Catana791/Fading-Revelations#43]
**Describe the bug**
Some errors occure 

**To Reproduce**
I just downloaded the mod and restarted my game. Also I had other mods installed too

**Expected behavior**
It should show some errors after loading up mindustry 

**Screenshots**
![Screenshot_20230416-214141_Mindustry](https://user-images.githubusercontent.com/105506091/232325978-2a1c92ac-6dab-498d-84be-be54b76eeec7.jpg)

**Smartphone**
 - Device: Samsung Galaxy M30s
 - OS: Android
 - Browser: Chrome
 - Version: Android 11

**Tablet**
 - Device: Samsung Galaxy Tab A7
 - OS: Android
 - Browser: Chrome
 - Version: Android 12

**Comment by Catana791** [comment]
Please reinstall the mod again. I was doing some development and missed a few little things which are fixed now.
