### ISSUE TITLE
Resprite Carrier Flagship it is ugly af

### ISSUE THREAD

**Issue by Catana791** [Catana791/Fading-Revelations#5]

**Comment by Rem-Armiger** [comment]
This is the first thing I did hope it's good enough the problems, possible fixes and, suggestion will be at the very bottom of the note when its finished.Sent from my Galaxy
-------- Original message --------From: Fresh791 <notifications@github.com> Date: 2/12/21  4:22 PM  (GMT+08:00) To: Fresh791/mindustry-extended <mindustry-extended@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Fresh791/mindustry-extended] Resprite Carrier Flagship it is ugly af (#5)

**Comment by Catana791** [comment]
Done. Happy with the result.
