### ISSUE TITLE
Bug/Issue

### ISSUE THREAD

**Issue by Felixolol** [Catana791/Fading-Revelations#53]
**Describe the bug**
i downloaded the mod and some errors appeared

**To Reproduce**
i just restarted the game to load it and it happens every time
i also had a mod called "project unity" installed

**Expected behavior**
when i load the game the error appears

**Screenshots**

![Screenshot_212](https://user-images.githubusercontent.com/132362837/235672228-00c3c7f3-e5b2-4dca-a274-66ec2cb0d1e6.png)
![Screenshot_213](https://user-images.githubusercontent.com/132362837/235672281-25af469e-ddb0-4362-95be-1d38e94969b3.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser opera gx
 - Version 141.3

**Smartphone (please complete the following information):**
 - Device: oppo 153
 - OS: android
 - Browser opera gx
 - Version android 11

**Comment by Catana791** [comment]
Hello there!
SkyMeshes aren't supported in json for the version you are using. 
Please update your game to the latest version (143.1). That should fix it.
