### ISSUE TITLE
Bug/Issue

### ISSUE THREAD

**Issue by Up-an-Down** [Catana791/Fading-Revelations#57]
**Describe the bug**
My items dont appear in tech tree
**To Reproduce**
1. Go to tech tree

**Screenshots**
![image](https://github.com/Fresh791/Fading-Revelations/assets/104922829/4094a433-f709-4872-af4d-50b72b39628a)
![image](https://github.com/Fresh791/Fading-Revelations/assets/104922829/28f42e18-5ec3-4c20-9180-d0cd030e5c1c)

 - OS: Windows
 - Version 144.1

**Comment by Catana791** [comment]
If I had to guess, that's because you are on a planet that isn't vanilla. 

Try to go to Seepulo and see if you can use your core resources from there.
